apiVersion: schema.esdm.io/core/v1
kind: event
name: group-cataloged
scope:
  domain: sport
  boundedContext: sport
  aggregate: group
data: {}
---
apiVersion: schema.esdm.io/core/v1
kind: event
name: group-edited
scope:
  domain: sport
  boundedContext: sport
  aggregate: group
data: {}
---
apiVersion: schema.esdm.io/core/v1
kind: event
name: group-archived
scope:
  domain: sport
  boundedContext: sport
  aggregate: group
data: {}
