apiVersion: schema.esdm.io/core/v1
kind: command
name: catalog-instrument
scope:
  domain: sport
  boundedContext: sport
  aggregate: instrument
data: {}
publishes:
  - instrument-cataloged
actors:
  - user
---
apiVersion: schema.esdm.io/core/v1
kind: command
name: edit-instrument
scope:
  domain: sport
  boundedContext: sport
  aggregate: instrument
data: {}
publishes:
  - instrument-edited
actors:
  - user
---
apiVersion: schema.esdm.io/core/v1
kind: command
name: archive-instrument
scope:
  domain: sport
  boundedContext: sport
  aggregate: instrument
data: {}
publishes:
  - instrument-archived
actors:
  - user
---
apiVersion: schema.esdm.io/core/v1
kind: command
name: catalog-apparatus
scope:
  domain: sport
  boundedContext: sport
  aggregate: apparatus
data: {}
publishes:
  - apparatus-cataloged
actors:
  - user
---
apiVersion: schema.esdm.io/core/v1
kind: command
name: edit-apparatus
scope:
  domain: sport
  boundedContext: sport
  aggregate: apparatus
data: {}
publishes:
  - apparatus-edited
actors:
  - user
---
apiVersion: schema.esdm.io/core/v1
kind: command
name: archive-apparatus
scope:
  domain: sport
  boundedContext: sport
  aggregate: apparatus
data: {}
publishes:
  - apparatus-archived
actors:
  - user
