apiVersion: schema.esdm.io/core/v1
kind: command
name: catalog-apparatus
scope:
  domain: sport
  boundedContext: sport
  aggregate: apparatus
data: {}
publishes:
  - apparatus-cataloged
actors:
  - user
