apiVersion: schema.esdm.io/core/v1
kind: command
name: archive-apparatus
scope:
  domain: sport
  boundedContext: sport
  aggregate: apparatus
data:
  type: object
  properties:
    id:
      type: string
      format: uuid
      description: "Unique identifier of the apparatus to archive"
  required:
    - id
constraints:
  - name: apparatus-exists
    rule: An apparatus needs to exist (check by id)
publishes:
  - apparatus-archived
actors:
  - user
