apiVersion: schema.esdm.io/core/v1
kind: event
name: instrument-archived
scope:
  domain: sport
  boundedContext: sport
  aggregate: instrument
data:
  type: object
  properties:
    id:
      type: string
      format: uuid
      description: "Unique identifier of the instrument"
  required:
    - id
