apiVersion: schema.esdm.io/core/v1
kind: event
name: apparatus-edited
scope:
  domain: sport
  boundedContext: sport
  aggregate: apparatus
data:
  type: object
  properties:
    id:
      type: string
      format: uuid
      description: "Unique identifier"
    title:
      type: string
      description: "Name of the apparatus"
    slug:
      type: string
      description: "URL-friendly unique identifier"
    description:
      type: string
      description: "Optional description"
  required:
    - id
