apiVersion: schema.esdm.io/core/v1
kind: command
name: archive-position
scope:
  domain: sport
  boundedContext: sport
  aggregate: position
data: {}
publishes:
  - position-archived
actors:
  - user
