apiVersion: schema.esdm.io/core/v1
kind: event
name: position-cataloged
scope:
  domain: sport
  boundedContext: sport
  aggregate: position
data: {}
---
apiVersion: schema.esdm.io/core/v1
kind: event
name: position-edited
scope:
  domain: sport
  boundedContext: sport
  aggregate: position
data: {}
---
apiVersion: schema.esdm.io/core/v1
kind: event
name: position-archived
scope:
  domain: sport
  boundedContext: sport
  aggregate: position
data: {}
