apiVersion: schema.esdm.io/core/v1
kind: aggregate
name: phase-model
scope:
  domain: sport
  boundedContext: sport
identifiedBy:
  source: generated
  generator: uuid
state: {}
invariants:
  - name: phases-sequential
    rule: "Phases must be ordered sequentially without gaps"
---
apiVersion: schema.esdm.io/core/v1
kind: aggregate
name: function-model
scope:
  domain: sport
  boundedContext: sport
identifiedBy:
  source: generated
  generator: uuid
state: {}
---
apiVersion: schema.esdm.io/core/v1
kind: aggregate
name: constitutive-structure
scope:
  domain: sport
  boundedContext: sport
identifiedBy:
  source: generated
  generator: uuid
state: {}
