apiVersion: schema.esdm.io/core/v1
kind: aggregate
name: phase-model
description: "The phase model by Meinel & Schnabel"
scope:
  domain: sport
  boundedContext: sport
identifiedBy:
  source: generated
  generator: uuid
state: {}
invariants:
  - name: phases-sequential
    rule: "Phases must be ordered sequentially without gaps"
---
apiVersion: schema.esdm.io/core/v1
kind: aggregate
name: function-model
description: "The function and function phase model by Göhner"
scope:
  domain: sport
  boundedContext: sport
identifiedBy:
  source: generated
  generator: uuid
state: {}
---
apiVersion: schema.esdm.io/core/v1
kind: aggregate
name: constitutive-structure
description: "The constitutive movement structure by Kassat"
scope:
  domain: sport
  boundedContext: sport
identifiedBy:
  source: generated
  generator: uuid
state: {}
