apiVersion: schema.esdm.io/core/v1
kind: command
name: construct-constitutive-structure
scope:
  domain: sport
  boundedContext: sport
  aggregate: constitutive-structure
data: {}
publishes:
  - constitutive-structure-constructed
actors:
  - user
