apiVersion: schema.esdm.io/core/v1
kind: read-model
name: group
scope:
  domain: sport
  boundedContext: sport
projections:
  - boundedContext: sport
    aggregate: group
    event: group-cataloged
    rule: "Project the group when it is cataloged"
  - boundedContext: sport
    aggregate: group
    event: group-edited
    rule: "Update group details"
  - boundedContext: sport
    aggregate: group
    event: group-archived
    rule: "Mark group as archived"
schema: {}
