apiVersion: schema.esdm.io/core/v1
kind: command
name: upload-picture
scope:
  domain: sport
  boundedContext: sport
  aggregate: skill
data: {}
publishes:
  - picture-uploaded
actors:
  - user
---
apiVersion: schema.esdm.io/core/v1
kind: command
name: upload-video
scope:
  domain: sport
  boundedContext: sport
  aggregate: skill
data: {}
publishes:
  - video-uploaded
actors:
  - user
---
apiVersion: schema.esdm.io/core/v1
kind: command
name: delete-media
scope:
  domain: sport
  boundedContext: sport
  aggregate: skill
data: {}
publishes:
  - media-deleted
actors:
  - user
