apiVersion: schema.esdm.io/core/v1
kind: event
name: picture-uploaded
scope:
  domain: sport
  boundedContext: sport
  aggregate: skill
data: {}
---
apiVersion: schema.esdm.io/core/v1
kind: event
name: video-uploaded
scope:
  domain: sport
  boundedContext: sport
  aggregate: skill
data: {}
---
apiVersion: schema.esdm.io/core/v1
kind: event
name: media-deleted
scope:
  domain: sport
  boundedContext: sport
  aggregate: skill
data: {}
