apiVersion: schema.esdm.io/core/v1
kind: command
name: change-position
scope:
  domain: sport
  boundedContext: sport
  aggregate: skill
data: {}
publishes:
  - start-position-changed
  - end-position-changed
actors:
  - user
