apiVersion: schema.esdm.io/core/v1
kind: command
name: catalog-skill
scope:
  domain: sport
  boundedContext: sport
  aggregate: skill
data: {}
publishes:
  - skill-cataloged
actors:
  - user
---
apiVersion: schema.esdm.io/core/v1
kind: command
name: change-position
scope:
  domain: sport
  boundedContext: sport
  aggregate: skill
data: {}
publishes:
  - start-position-changed
  - end-position-changed
actors:
  - user
---
apiVersion: schema.esdm.io/core/v1
kind: command
name: record-source
scope:
  domain: sport
  boundedContext: sport
  aggregate: skill
data: {}
publishes:
  - source-recorded
actors:
  - user
---
apiVersion: schema.esdm.io/core/v1
kind: command
name: unrecord-source
scope:
  domain: sport
  boundedContext: sport
  aggregate: skill
data: {}
publishes:
  - source-unrecorded
actors:
  - user
