apiVersion: schema.esdm.io/core/v1
kind: command
name: amend-instructional-progression
scope:
  domain: sport
  boundedContext: sport
  aggregate: skill
data: {}
publishes:
  - instructional-progression-amended
actors:
  - user
