apiVersion: schema.esdm.io/core/v1
kind: event
name: instructional-progression-constructed
scope:
  domain: sport
  boundedContext: sport
  aggregate: skill
data: {}
---
apiVersion: schema.esdm.io/core/v1
kind: event
name: instructional-progression-amended
scope:
  domain: sport
  boundedContext: sport
  aggregate: skill
data: {}
---
apiVersion: schema.esdm.io/core/v1
kind: event
name: tutorial-linked
scope:
  domain: sport
  boundedContext: sport
  aggregate: skill
data: {}
---
apiVersion: schema.esdm.io/core/v1
kind: event
name: tutorial-unlinked
scope:
  domain: sport
  boundedContext: sport
  aggregate: skill
data: {}
---
apiVersion: schema.esdm.io/core/v1
kind: event
name: error-cataloged
scope:
  domain: sport
  boundedContext: sport
  aggregate: skill
data: {}
