apiVersion: schema.esdm.io/core/v1
kind: command
name: suggest-sport
scope:
  domain: sport
  boundedContext: sport
  aggregate: sport
data: {}
publishes:
  - sport-suggested
actors:
  - user
---
apiVersion: schema.esdm.io/core/v1
kind: command
name: approve-sport
scope:
  domain: sport
  boundedContext: sport
  aggregate: sport
data: {}
publishes:
  - sport-approved
actors:
  - admin
---
apiVersion: schema.esdm.io/core/v1
kind: command
name: reject-sport
scope:
  domain: sport
  boundedContext: sport
  aggregate: sport
data: {}
publishes:
  - sport-rejected
actors:
  - user
---
apiVersion: schema.esdm.io/core/v1
kind: command
name: archive-sport
scope:
  domain: sport
  boundedContext: sport
  aggregate: sport
data: {}
publishes:
  - sport-archived
actors:
  - admin
---
apiVersion: schema.esdm.io/core/v1
kind: command
name: associate-position
scope:
  domain: sport
  boundedContext: sport
  aggregate: sport
data: {}
publishes:
  - position-associated
actors:
  - user
---
apiVersion: schema.esdm.io/core/v1
kind: command
name: dissociate-position
scope:
  domain: sport
  boundedContext: sport
  aggregate: sport
data: {}
publishes:
  - position-dissociated
actors:
  - user
---
apiVersion: schema.esdm.io/core/v1
kind: command
name: associate-group
scope:
  domain: sport
  boundedContext: sport
  aggregate: sport
data: {}
publishes:
  - group-associated
actors:
  - user
---
apiVersion: schema.esdm.io/core/v1
kind: command
name: use-instrument
scope:
  domain: sport
  boundedContext: sport
  aggregate: sport
data: {}
publishes:
  - instrument-used
actors:
  - user
---
apiVersion: schema.esdm.io/core/v1
kind: command
name: withdraw-instrument
scope:
  domain: sport
  boundedContext: sport
  aggregate: sport
data: {}
publishes:
  - instrument-withdrawn
actors:
  - user
---
apiVersion: schema.esdm.io/core/v1
kind: command
name: use-apparatus
scope:
  domain: sport
  boundedContext: sport
  aggregate: sport
data: {}
publishes:
  - apparatus-used
actors:
  - user
---
apiVersion: schema.esdm.io/core/v1
kind: command
name: withdraw-apparatus
scope:
  domain: sport
  boundedContext: sport
  aggregate: sport
data: {}
publishes:
  - apparatus-withdrawn
actors:
  - user
